### ISSUE TITLE
Final graded assessment: Introduction to Android mobile application development attempts

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/MetaAndroid#1]
1:

![SNAG-0160](https://user-images.githubusercontent.com/428820/196039079-59117bc7-37db-43dc-b8a0-8fa181938a1f.png)

2. and winner:

![SNAG-0161](https://user-images.githubusercontent.com/428820/196039327-c16978b0-d2dc-4ed1-82e0-0803a2222609.png)

**Comment by dennislamcv1** [comment]
This part also changed questions
