### ISSUE TITLE
Introduction to Mobile Development/Graded assessment attemtps

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/MetaAndroid#3]
![1](https://user-images.githubusercontent.com/428820/197542358-7d2af134-958d-4ba8-a396-f39a56894e5d.png)

![22](https://user-images.githubusercontent.com/428820/197542510-8746c634-dedf-400b-90b4-37600b0d5e84.png)

![60](https://user-images.githubusercontent.com/428820/197542661-d5885537-465c-49de-8807-81df13438356.png)

**Comment by dennislamcv1** [comment]
Questions will change for this part
